# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
format = '[$user](bold yellow)@'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold red) '
disabled = false
